### ISSUE TITLE
Compute space before end of the final page

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#4]
adapt this code: https://github.com/diverse-project/varylatex/blob/master/optimizer.py#L149-L192 
so that it can work in general 

it's related to #1 and #3: it's an information we can compute/gather in a CSV file

**Comment by c-a-m-o** [comment]
Done in commit 8abf90221ff3be0ea19444bb92d8a07d028409b3
Instead of computing the space before the end, the script returns the largest empty space in the last page. This prevents documents with things at the bottom of the page like the page number) from always outputting the same value. The optional `page_number` parameter helps differentiate between the two cases.
