### ISSUE TITLE
support/demonstration with overleaf

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#7]
the user story is "given me an URL of an overleaf repo (read only?), I can execute varylatex" and compile different PDF variants... 
I know overleaf has a kind of "git" and it's possible to download the content of a repo. 

I propose to have an examplar overleaf with the "FSE" case

**Comment by c-a-m-o** [comment]
For now it doesn't seem to be possible to automatically retrieve a project from Overleaf.
Web scraping with an invite link appears blocked by the website.
The `git` feature is only possible with a subscription or an old Overleaf account but it should be possible to support links to `git`projects instead of Overleaf projects.

**Comment by c-a-m-o** [comment]
Added in commit b2789168ddb27dd946b7872a49f40634632c3276.
There is now an option in the script (`-ol` or `--overleaf`) where the user can specify an invite key (the letters after the `/read/` in the **read-only** invite link of the project). It downloads the project and runs varylatex on it.
This means that the project must
- include the `macros` and `values` files in the document
- contain a `variables.json` file
